#!/bin/bash

docker run --rm \
  --gpus all \
  --runtime=nvidia \
  --mount "type=bind,src=$(pwd)/run-data,dst=/data" \
	--publish "127.0.0.1:8880:5432" \
	--publish "127.0.0.1:8881:8080" \
	--publish "127.0.0.1:8888:8888" \
	--hostname "synthflow" \
  --name "synthflow" \
  -u root \
	-it synthflow bash --init-file /data/src/synthflow/scripts/root-on-start.sh

