#!/bin/bash

specialization="$1"

docker run --rm \
  --gpus 2 \
  --mount "type=bind,src=$(pwd)/run-data,dst=/data" \
	--publish "127.0.0.1:8880:5432" \
	--publish "127.0.0.1:8881:8080" \
	--hostname "synthflow" \
	-it synthflow-"$specialization" bash --init-file /data/scripts/root-on-start.sh

